version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"

jobs:
  # Run static Go-related checks, e.g. code formatting.
  go-check:
    executor: go-container
    steps:
      - checkout
      - run:
          name: Install goimports tool
          command: |
            go get -u golang.org/x/tools/cmd/goimports
            echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
      - run:
          name: Check Go format
          command: python ./scripts/check_fmt.py
      - run:
          name: Check Go imports
          command: python ./scripts/check_imports.py

  # Run all Go tests.
  go-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Run all tests
          command: go test -v ./...

  # Verify that the requirements for creating a new release are met.
  pre-release-check:
    executor: go-container
    steps:
      - checkout
      - run:
          name: Check release in CHANGELOG.md
          command: python ./scripts/check_changelog.py

  # Build verless binaries for multiple platforms.
  build:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Build binaries
          command: python ./scripts/build.py
      - run:
          name: Copy archives to /tmp/artifacts
          command: |
            mkdir /tmp/artifacts && cp target/*.* /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - verless-*

  # Release the packaged binaries to GitHub.
  release-github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: Install Python
          command: apk add --no-cache python2
      #- run:
      #    name: Get the release changelog
      #    command: echo "export CHANGELOG=$(python ./scripts/print_changelog.py)" >> $BASH_ENV
      - run:
          name: Publish GitHub release
          command: |
            ghr -t "${GITHUB_TOKEN}" \
                -u "${CIRCLE_PROJECT_USERNAME}" \
                -r "${CIRCLE_PROJECT_REPONAME}" \
                -c "${CIRCLE_SHA1}" \
                -b $(python ./scripts/print_changelog.py) \
                -delete "${CIRCLE_TAG}" \
                /tmp/artifacts

workflows:
  version: 2
  # The basic CI workflow for single commits and opened PRs.
  verless-ci:
    jobs:
      - go-check
      - go-test:
          requires:
            - go-check
  # The workflow for delivering the verless application.
  verless-cd:
    jobs:
      - pre-release-check:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - pre-release-check
          filters:
            tags:
              only: /v.*/
      - release-github:
          requires:
            - build
          filters:
            tags:
              only: /v.*/