version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"
      GOPROXY: "https://proxy.golang.org"

jobs:
  # Run static Go-related checks, e.g. code formatting.
  go-check:
    executor: go-container
    steps:
      - checkout
      - run:
          name: Check Go format
          command: python ./scripts/check_fmt.py
      - run:
          name: Check Go imports
          command: python ./scripts/check_imports.py

  # Run all Go tests.
  go-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Run all tests
          command: go test -v ./...

  # Build verless binaries for multiple platforms.
  build:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodules-v1-{{ checksum "go.mod" }}
            - gomodules-v1-
      - run:
          name: Download dependencies
          command: go mod download
      - save_cache:
          key: gomodules-v1-{{ checksum "go.mod" }}
          paths: /go/pkg
      - run:
          name: Build binaries
          command: python ./scripts/build.py
      - run:
          name: Copy archives to /tmp
          command: cp target/*.* /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - verless-*

  # Release the packaged binaries to GitHub.
  release-github:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Publish GitHub release
          command: |
            ghr -t "${GITHUB_TOKEN}" \
                -u "${CIRCLE_PROJECT_USERNAME}" \
                -r "${CIRCLE_PROJECT_REPONAME}" \
                -c "${CIRCLE_SHA1}" \
                -delete "${CIRCLE_TAG}" \
                /tmp

workflows:
  version: 2
  # The basic CI workflow for single commits and opened PRs.
  verless-ci:
    jobs:
      - go-check
      - go-test:
          requires:
            - go-check
  # The workflow for delivering the verless application.
  verless-cd:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release-github:
          requires:
            - build